### ISSUE TITLE
Invalid selected state for select control

### ISSUE THREAD

**Issue by trinvh** [netojose/laravel-bootstrap-4-forms#10]
I found a bug with select control.

You can look at FormService.php file, line `371`.

Current code:

```
 foreach ($this->_props['options'] as $value=> $label){
            $checked = $value== $value ? ' selected' : '';
            $options .= '<option value="'.$value.'"'.$checked.'>'.$label.'</option>';
        }
```

It should be:

```
foreach ($this->_props['options'] as $option => $label){
            $checked = $option == $value ? ' selected' : '';
            $options .= '<option value="'.$option.'"'.$checked.'>'.$label.'</option>';
        }
```

Please merge this code to the next release.
Also, do you have a plan to support select with multiple?

Thanks

**Comment by netojose** [comment]
@trinvh , About this bug, [as you can see here](https://github.com/netojose/laravel-bootstrap-4-forms/blob/master/src/FormService.php#L372), I fixed, and pushed, but unfortunately I didn't create a new version. So, the composer doesn't update. 

Please, remove the package, and install againg, to fix this in your project.

**Comment by netojose** [comment]
Select multiple is available with: https://github.com/netojose/laravel-bootstrap-4-forms#select-multiple
