### ISSUE TITLE
Problemas com select e relacionamentos

### ISSUE THREAD

**Issue by lbenedette** [netojose/laravel-bootstrap-4-forms#12]
Estou tentando criar um select multiple que define as roles que meus usuários possuem.
`{!! Form::select('role_ids[]', $roleOptions, __('app.users.labels.roles'))->params(['multiple' => true]) !!}`

Porém no edit utilizando a função fill()
`{!! Form::open()->put()->url('/users/' . $user->id . '/edit')->fill($user) !!}`

O form gerado coloca todas as opções do select como selecionadas, ao invés das opções que o usuário possui, sendo que Role é um relacionamento (N para N).
Isto seria algum tipo de bug ou erro, ou existe alguma configuração para solucionar este problema?

**Comment by rifton007** [comment]
Hi @lbenedette,

This problem has been resolve in my last pull request.
It'll be soon available.

**Comment by netojose** [comment]
Yes, today early I fixed other bug (input class bug), on 1.0.1 version, and tonight I will merge the pull request to solve this bug)

**Comment by netojose** [comment]
Fixed on version 2, now supports select multiple.

https://github.com/netojose/laravel-bootstrap-4-forms/releases/tag/2.0.0

Thanks @rifton007 for the colaboration.
