### ISSUE TITLE
FormService.php problem

### ISSUE THREAD

**Issue by Hydro8** [netojose/laravel-bootstrap-4-forms#19]
Hi

I just test your package with my laravel 5.4 and I've got this error no matter what code I add to my page :

syntax error, unexpected ':', expecting ';' or '{'
in FormService.php line 65

Do you know how to fix that ?

Thank

**Comment by netojose** [comment]
Hi @Hydro8 , thanks for reporting.
This erros was not related to laravel Version, but to PHP version. The error line [is here](https://github.com/netojose/laravel-bootstrap-4-forms/blob/master/src/FormService.php#L65), I'm using the __return type declarations__ feature, [one of new features on php, available on PHP 7](http://php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration).

Please, update your php to version 7.0
