### ISSUE TITLE
Could not find package netojose/laravel-bootstrap-4-forms

### ISSUE THREAD

**Issue by hoekie** [netojose/laravel-bootstrap-4-forms#2]
Hi,

When I try to install your package from composer I get the following error:

`Could not find package netojose/laravel-bootstrap-4-forms at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability`

It looks like you have a type mismatch in you composer.json file:

`"name": "netojose/laravel-bootstrap4-forms",`

should be:

`"name": "netojose/laravel-bootstrap-4-forms",`

The package itself seems to work as aspected except for the selectbox:

All the options of the selectbox gets the 'selected' property after populating.

 **Some Questions:**
1. I like to add a default value to the select box.
Something like 'Please select a category'.
2. Could'nt find the option to add an 'old value' to the selectbox so an item is selected when using the selectbox in an edit form.

Is it possible to add those features?

Thank you for this great package!

Richard

**Comment by netojose** [comment]
@hoekie , thanks for comment. I'm fixing the composer problems. About your questions, the features are already available:

#####  I like to add a default value to the select box. something like 'Please select a category'.
you can use a array item with a empty key:
```
{!!Form::open()->route('user.add')->data(['city' => 2])!!}
{!!Form::select('city', ['' => 'Please select a city', 1 => 'Gotham City', 2 => 'Springfield'], 'Escolha sua cidade')!!}
{!!Form::close()}
```

##### Could'nt find the option to add an 'old value' to the selectbox so an item is selected when using the selectbox in an edit form.

You can use data() method chainning on Form::open():
```
{!!Form::open()->route('user.add')->data(['city' => 2])!!}
{!!Form::select('city', [1 => 'Gotham City', 2 => 'Springfield'], 'Choose your city')!!}
{!!Form::close()}
```

**Comment by netojose** [comment]
@hoekie , I fixed the problem. You can use the package normally, and you was right, the package name was wrong.
Thanks again for you cooperation!!

**Comment by hoekie** [comment]
Hi @netojose, Thank you for the info on how to use the selectbox.
It works like a charm!
I'm glad I could help to fix the problem.
