### ISSUE TITLE
Color classes doesn't get added

### ISSUE THREAD

**Issue by henninghorn** [netojose/laravel-bootstrap-4-forms#22]
Hi @netojose 

I have tried using the example from the docs:

```php
{!!Form::submit('Awesome button')->id('my-btn')->disabled()->danger()->lg()!!}
```

The `id()`, `disabled()` and `lg()` methods works, except `danger()` (or `color('danger)`), it just doesn't work. Also, the btn class doesn't seem to be added either.

I have tried looking through the source, but I can't see exactly where the problem is.

**Comment by netojose** [comment]
@henninghorn , thanks for report the problem. Looking at the code, I could not see the problem. Today later, I will run on my machine using your example, to reproduce the error and fix it.

**Comment by netojose** [comment]
Fixed on [this pull request](https://github.com/netojose/laravel-bootstrap-4-forms/pull/28).
Thanks @fchalal !
