### ISSUE TITLE
Button appearance broken in 2.0.2

### ISSUE THREAD

**Issue by mattlibera** [netojose/laravel-bootstrap-4-forms#29]
In 2.0.2 buttons are being rendered with the `form-control` class, which makes them 100% width. They also don't seem to respond to the color ('warning', 'danger', etc.) or size ('sm', 'lg', etc.) classes.

```
// all of these give me full-width, white button
Form::submit('Update config')
Form::submit('Update config', 'primary', 'lg')
Form::button('Update config', 'primary', 'lg')
```

Is this related to some of the refactoring in 2.0.2?

edit: downgrading to 2.0.0 does fix the first one above. the others may be related to #22

**Comment by netojose** [comment]
Fixed [here](https://github.com/netojose/laravel-bootstrap-4-forms/commit/7793ad7788acb7b32ca5582e8c9f5c64728be379).

Thanks, @mattlibera !!!
