### ISSUE TITLE
Select - all options receive 'selected' when no value present

### ISSUE THREAD

**Issue by mattlibera** [netojose/laravel-bootstrap-4-forms#3]
When generating a select box, and using it with no previous input from the request (e.g. in a "create new" scenario), all options receive the 'checked' flag, which results in the last option being the selected option by default.

I think I have located the problem and will try and submit a pull request shortly.

**Comment by netojose** [comment]
Fixed [here](https://github.com/netojose/laravel-bootstrap-4-forms/pull/4). Thanks @mattlibera !!!
