### ISSUE TITLE
File input class should be "form-control-file"

### ISSUE THREAD

**Issue by oscar-ol** [netojose/laravel-bootstrap-4-forms#30]
```
{!! Form::file('logo','Logo') !!}  

<div class="form-group">
<label for="logo">Logo</label>
<input name="logo" autocomplete="logo" id="logo" class="form-control" type="file">
</div>
```

> Bootstrap doc: For file inputs, swap the .form-control for .form-control-file.

**Comment by netojose** [comment]
Fixed [here](https://github.com/netojose/laravel-bootstrap-4-forms/commit/a289717cf1a55e7f0dcff5ee4a665114a83b4b4e).

Thanks @oscar-ol
