### ISSUE TITLE
Version 2.0.3 is not installed correctly

### ISSUE THREAD

**Issue by oscar-ol** [netojose/laravel-bootstrap-4-forms#33]
- Laravel 5.6
- composer require netojose/laravel-bootstrap-4-forms
- When loading a view: Class 'NetoJose\Bootstrap4Forms\FormService' not found

If I change to version 2.0.2 in composer.json, it works fine!

**Comment by oscar-ol** [comment]
I think your namespace in composer.json should be CamelCase "NetoJose".
If I change it in \vendor\composer\autoload* files, and in composer.json, it works.

**Comment by netojose** [comment]
@oscar-ol , problem solved. Please, uninstall and install again. The problem was because I accepted another pull request, and the namespace was changed.

Thanks!
