### ISSUE TITLE
->require() not working

### ISSUE THREAD

**Issue by vimalmistry** [netojose/laravel-bootstrap-4-forms#34]
I dont know why but is not working on my code. Other chaining methods are working fine.

**Comment by vimalmistry** [comment]
And how to customize form class etc??

**Comment by netojose** [comment]
Hi @vimalmistry , thanks for reporting. I will look this bug. And, about your question, you can add any attribute in inputs, just using [attrs->() method](https://github.com/netojose/laravel-bootstrap-4-forms#custom-attributes), like this:
```
{!!Form::text('name', 'Name')->attrs(['class' => 'MY_CUSTOM_CLASS', 'data-foo' => 'bar', 'rel'=> 'baz'])!!}
```

**Comment by netojose** [comment]
Good idea @vimalmistry , I will fix this bug reported by you, and create another issue to request this, using something like this:
```
{!!Form::text('username', 'Username')->naked()!!}
```

For now, to use *required*, while this bug is not solved, you can use attrs to perform this

```
{!!Form::text('username', 'Username')->attrs(['required' => true])!!}
```
