### ISSUE TITLE
Support for html5 text types

### ISSUE THREAD

**Issue by lakerobin** [netojose/laravel-bootstrap-4-forms#35]
It appears that only number, email and range types are available.

Is there a way to create a input with type of say url or tel?

**Comment by netojose** [comment]
Yes, you can do using **type()** method, this way:

```php
{!!Form::text('phone', 'Phone number')->type('tel')!!}
{!!Form::text('url', 'Website url')->type('url')!!}
```

**Comment by str** [comment]
It feels you have to keep track of which types are ::$type() (like hidden, password, etc), and wich ones you have to add it after. Can we make it so we use the same format in all of them?

Thank you.
