### ISSUE TITLE
required attribute does not work

### ISSUE THREAD

**Issue by lakerobin** [netojose/laravel-bootstrap-4-forms#37]
Setting the required attribute by calling required method does not generate the corresponding code.

    {!!Form::text('name', 'Name')->required()!!}

generates

    <div class="form-group ">
        <label for="name">Name</label>
        <input type="text" name="name" autocomplete="name" id="name" class="form-control">
    </div>
 
required attribute is missing.

**Comment by lakerobin** [comment]
Added a PR to fix this

**Comment by netojose** [comment]
Thanks!

**Comment by netojose** [comment]
Sorry @ricardovigatti , I fixed this (and other issues), and tomorrow I will create a new version.
I'm back! And I will solve all opened issues and keep improving this package

**Comment by ricardovigatti** [comment]
Ok, very nice! Let me know if you need any help
