### ISSUE TITLE
Element order

### ISSUE THREAD

**Issue by separd** [netojose/laravel-bootstrap-4-forms#47]
Is possible to chage order of rendered elements - first input and second label?
```
<div class="form-label-group">
<input type="email" id="inputEmail" class="form-control" placeholder="Email address">
<label for="inputEmail">Email address</label>
</div>
```

**Comment by netojose** [comment]
Nope, we are following the markup according to the [Bootstrap 4](https://getbootstrap.com/docs/4.2/components/forms/) official documentation
