### ISSUE TITLE
Custom class and/or attributes for the .form-group div?

### ISSUE THREAD

**Issue by ataylor32** [netojose/laravel-bootstrap-4-forms#48]
Looking at the `FormBuilder` class' `_renderWarpperCommomField` method (that method's name has a typo, by the way), it appears that the `<div>` is hard-coded to use `<div class="form-group ">`. It would be nice to be able to add another class or even a custom attribute like `id` or `data-foo` or whatever.

**Comment by impactcolor** [comment]
On the whole group or individual form elements? @ataylor32 
{!!Form::text('name', 'Name')->params(['class' => 'form-control map-input'])!!}

**Comment by netojose** [comment]
@ataylor32 , thank you for you idea, I implemented [this feature](https://github.com/netojose/laravel-bootstrap-4-forms#custom-attributes-in-wrapper-div-div-classform-groupdiv) and already is available.

And I fixed the typo error, thanks too.
