### ISSUE TITLE
Custom attributes not work

### ISSUE THREAD

**Issue by mkswebdev** [netojose/laravel-bootstrap-4-forms#50]
netojose/laravel-bootstrap-4-forms    2.0.5 

{!!Form::text('name', 'Name')->attrs(['data-foo' => 'bar', 'rel'=> 'baz'])!!}
{!!Form::open()->attrs(['data-foo' => 'bar', 'rel'=> 'baz'])!!}

not work. Please check.

**Comment by netojose** [comment]
@mkswebdev , fixed at 2.0.6 version. Thanks!!!
