### ISSUE TITLE
Horizontal form / columns for lables

### ISSUE THREAD

**Issue by str** [netojose/laravel-bootstrap-4-forms#53]
Is there a way to render columns to put the label next to the input? Like documented here:

https://getbootstrap.com/docs/4.2/components/forms/#horizontal-form

**Comment by netojose** [comment]
@str , I working on a hard refactoring, and adding this feature. Thanks! :)

**Comment by SystemF** [comment]
Is there any progress for this feature? It depends for me if I'll use this package or not. The package itself works great, this is the only (major) downside. Thanks!

**Comment by agharium** [comment]
Any progress on this feature? Need it so much!

**Comment by netojose** [comment]
Done, you can perform this when opening the form:

```php
{!! Form::open()->inline()) !!}
```

**Comment by SystemF** [comment]
Excellent! Thanks!

Op zo 16 jun. 2019 15:28 schreef José Neto <notifications@github.com>:

**Comment by str** [comment]
I think this is not working anymore.
I tried 

`
{!! Form::open()->formInline()) !!}
{!! Form::open()->inline()) !!}
{!! Form::open->inlineForm() !!}
`

and none shows a column/horizontal view
