### ISSUE TITLE
Checkboxes are marked :checked when chained value doesn't match checkbox value.

### ISSUE THREAD

**Issue by kynetiv** [netojose/laravel-bootstrap-4-forms#59]
A checkbox is marked `checked` just so long as there is ANY value returned from `_getValue()` and the type is `checkbox`. Is this right? This is occurring around line 778 of the FormBuilder.php:

```php
if (in_array($this->_type, ['radio', 'checkbox'])) {
    $value = $this->_getValue();
    if (
            $value && (
            $this->_type === 'checkbox' || $this->_type === 'radio' && $value === $this->_meta['value']
            )
    ) {
            $props['checked'] = true;
    }
}
```

Perhaps this needs to be simplified to just check  value matches the `_meta['value']`? (since we know it is of type radio or checkbox already)

```php
if (in_array($this->_type, ['radio', 'checkbox'])) {
    $value = $this->_getValue();
    if ($value && $value === $this->_meta['value'] ) {
        $props['checked'] = true;
    }
}

```

**Comment by netojose** [comment]
Fixed on 3.0.0 version. Please let me know if the error still exists.
