### ISSUE TITLE
Add support for <input type="datetime-local">

### ISSUE THREAD

**Issue by ataylor32** [netojose/laravel-bootstrap-4-forms#61]
Support on desktop browsers isn't that great ([source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#Browser_compatibility)), but it still makes sense to use in some projects. I would submit a PR for this myself, but it's not exactly straightforward due to the hyphen in `datetime-local`. I would really appreciate this input type being available in this excellent package!

**Comment by netojose** [comment]
You can do this:

```php
{!! Form::text('date', 'Date')->type('datetime-local') !!}
```
