### ISSUE TITLE
Error messages don't display for fields that use prefix and/or suffix

### ISSUE THREAD

**Issue by ataylor32** [netojose/laravel-bootstrap-4-forms#62]
If my form has a field that uses `prefix` or `suffix` and I submit it with an invalid value in that field, I get redirected back to the form as expected, but the error message doesn't appear. This might be something that @snickbit is interested in knowing about.

**Comment by snickbit** [comment]
This is actually fixed in my version but I haven't submitted a pull request yet. I'll do that now.

**Comment by netojose** [comment]
@ataylor32 , there is a new version available (3.0.0), please let me know if the issue still exists.
