### ISSUE TITLE
Possible to disable is-valid class?

### ISSUE THREAD

**Issue by ragulka** [netojose/laravel-bootstrap-4-forms#64]
I'm wondering if there's a way to disable adding the is-valid class automatically when the form is submitted and has errors? I'm only interested in displaying the errors and is-invalid class.

**Comment by notarun** [comment]
Just created a pull request here https://github.com/netojose/laravel-bootstrap-4-forms/pull/67

**Comment by netojose** [comment]
On new version 3, you can use ** disableValidation()** method:

https://github.com/netojose/laravel-bootstrap-4-forms/tree/3.0.0#disable-validation-messages

**Comment by netojose** [comment]
> Just created a pull request here #67

@notarun , Thanks for your pull request, I used him to put in the new version. Unfortunately, I could not merge because, on this new version, the project was an entire rewrite. WAs impossible maintain.

On this new code, your improvements will welcome. Thanks again!
