### ISSUE TITLE
Change rows of textarea

### ISSUE THREAD

**Issue by claysllanxavier** [netojose/laravel-bootstrap-4-forms#66]
How do I change the rows and cols of textarea input?

**Comment by jhermans76** [comment]
Something like this should work.

{!! Form::textarea('comment', 'Comment')->attrs(['rows'=>30,'cols'=>15]) !!}

**Comment by 1e4** [comment]
This doesn't work if the default values are set, I can add extra attributes but cannot change the rows. I assume it's linked to #44
