### ISSUE TITLE
Multiple forms on a page

### ISSUE THREAD

**Issue by 1e4** [netojose/laravel-bootstrap-4-forms#69]
Hey,

I have multiple forms on a page, whenever I submit one, I get the validation for the other as well, is there anyway to avoid this other than having them on separate pages?

![image](https://user-images.githubusercontent.com/3780490/59793291-12edbf80-92ce-11e9-8a9b-0dc50b72a76f.png)

```
    <div class="card mb-3">
        <div class="card-header">
            Update your email
        </div>
        <div class="card-body">
            {!! Form::open()->route('account.email')->post() !!}
            {!! Form::text('email', 'New Email')->type('email') !!}
            <p>
                Upon updating your current email, your account will require validation before actions can be made
            </p>
            {!! Form::submit('Update Email') !!}
            {!! Form::close() !!}
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            Update your Password
        </div>
        <div class="card-body">
            {!! Form::open()->route('account.password')->post() !!}
            {!! Form::text('new_password', 'New Password')->type('password') !!}
            {!! Form::text('new_password_confirmation', 'New Password Confirmation')->type('password') !!}
            {!! Form::text('current_password', 'Current Password')->type('password') !!}
            {!! Form::submit('Update Password') !!}
            {!! Form::close() !!}
        </div>
    </div>
```

**Comment by netojose** [comment]
Yes @1e4 , there is a way to fix this. Today I finished a new version of the package, and tomorrow I will update the documentation and put online. On the new version, there is a method can help you.

When I bump the new version, I will back here and tell you.

Thanks!

**Comment by 1e4** [comment]
Ah great, thanks so much. I currently moved them into separate tabs. Will
move them back when the update is our. Love the package 👍

Cheers, Ian

**Comment by netojose** [comment]
@1e4 , new version is available, and now, you can have solve this using named error bags:

https://github.com/netojose/laravel-bootstrap-4-forms/tree/3.0.0#error-bag
