### ISSUE TITLE
FormBuilder::errors() issue

### ISSUE THREAD

**Issue by malyar-m** [netojose/laravel-bootstrap-4-forms#71]
Hello! 

I installed your package on Laravel 5.4.36 but got next error during render input elements:

```
{!! Form::open()->url(route('users-update')) !!} // Ok 
{!! Form::close() !!} // Ok
```

But any attempt to call `{!! Form::text('name', 'Name') !!}` causes next error

`Method NetoJose\Bootstrap4Forms\FormService::__toString() must not throw an exception, caught TypeError: Return value of NetoJose\Bootstrap4Forms\FormBuilder::errors() must be an instance of Illuminate\Support\MessageBag, instance of Illuminate\Support\ViewErrorBag returned`

And could you insert information about the minimal supported version of PHP in the readme?
Because you wrote that this package available for Laravel framework started from v5.4 ([PHP >= 5.6.4](https://laravel.com/docs/5.4/installation)) and in the same moment you used `iterable` typehint that available from php 7.1 [(official documentation)](https://www.php.net/manual/en/language.types.iterable.php)
`
public function options(iterable $options = [], string $valueKey = null, string $idKey = null): FormService`

Thank you for your work!

**Comment by malyar-m** [comment]
> job

**Comment by netojose** [comment]
@malyar-m , thanks for your feedback. Just one tip, if you are using a route, you can do:
```php
{!! Form::open()->route('users-update') !!}
```
Instead of
```php
{!! Form::open()->url(route('users-update')) !!}
```

About the error reported by you, and about your suggestion on `options()` method, I think I will remove this typehint, to increase support.

I will do this tonight and build a new release. Once again, thanks!

**Comment by ataylor32** [comment]
I ran into this error too. This works:

```
{!! Form::open()->errorBag('foo') !!}
{!! Form::text('test', 'Test') !!}
{!! Form::close() !!}
```

But if I change `{!! Form::open()->errorBag('foo') !!}` to `{!! Form::open() !!}` then I get the error.

**Comment by netojose** [comment]
Solved at: https://github.com/netojose/laravel-bootstrap-4-forms/tree/3.0.2

Thanks, @ataylor32  and @malyar-m !
