### ISSUE TITLE
Field attributes are being applied to both the field and its label

### ISSUE THREAD

**Issue by ataylor32** [netojose/laravel-bootstrap-4-forms#73]
Here is my form:

```
{!! Form::open()->route('posts.update', [$post->id])->fill($post)->patch() !!}
{!! Form::text('title', 'Title')->attrs(['maxlength' => '255'])->required() !!}
{!! Form::textarea('body', 'Body')->attrs(['class' => 'wysiwyg'])->required() !!}
<input type="hidden" name="allow_comments" value="0">
{!! Form::checkbox('allow_comments', 'Allow comments?', '1')->wrapperAttrs(['class' => 'wrapper-allow_comments']) !!}
{!! Form::submit('Update Post') !!}
{!! Form::close() !!}
```

The `<label>` tag that gets generated for the `title` field by the above code is `<label maxlength="255" for="inp-title" class="">Title</label>` (notice it has `maxlength="255"`). Likewise, the `<label>` tag that gets generated for the `body` field by the above code is `<label class="wysiwyg" for="inp-body">Body</label>` (notice it has `class="wysiwyg"`). I would expect these attributes to be applied only to the fields, not their labels.

**Comment by netojose** [comment]
Fixed on **3.0.3 version**, thanks @ataylor32 !

**Tip**: In your code above, you can use hidden method, to create a hidden field, this way:
```php
{!!Form::hidden('allow_comments', '0')!!}
```
