### ISSUE TITLE
wrapperAttrs doesn't work with checkboxes

### ISSUE THREAD

**Issue by ataylor32** [netojose/laravel-bootstrap-4-forms#74]
Here is my form:

```
{!! Form::open()->route('posts.update', [$post->id])->fill($post)->patch() !!}
{!! Form::text('title', 'Title')->attrs(['maxlength' => '255'])->required() !!}
{!! Form::textarea('body', 'Body')->attrs(['class' => 'wysiwyg'])->required() !!}
<input type="hidden" name="allow_comments" value="0">
{!! Form::checkbox('allow_comments', 'Allow comments?', '1')->wrapperAttrs(['class' => 'wrapper-allow_comments']) !!}
{!! Form::submit('Update Post') !!}
{!! Form::close() !!}
```

The wrapper that gets generated for the `allow_comments` field by the above code is `<div class="form-check">`. Notice that it didn't apply my `wrapper-allow_comments` class.

**Comment by netojose** [comment]
Fixed on **3.0.3 version**, thanks @ataylor32 !

**Tip**: In your code above, you can use hidden method, to create a hidden field, this way:
```php
{!!Form::hidden('allow_comments', '0')!!}
```

**Comment by ataylor32** [comment]
Thanks for fixing the bug, and thanks for the tip! I tried your tip, but it didn't work. The hidden input always used the value of the model instance (0 or 1, whichever the model instance had). Also, its `id` attribute had a value of `inp-allow_comments`, which was the same as the checkbox's `id` attribute, and giving two different elements the same `id` attribute is invalid HTML.

**Comment by netojose** [comment]
@ataylor32 , the field will be filled with the model value, and this method doesn't allow override this. But... I think you can solve this problem and the id problem using other methods, you can try this:

```php
{!!Form::hidden('allow_comments')->value('0')->id('my-id')!!}
```

When you use `->value()`, has more precedence over `fill` values
